version: '3'
services:
  user_management:
    container_name: "user_management"
    build: .
    ports: 
      - "9000:9000"
    environment:
      - POSTGRES_DB=db_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: db_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: